  release:
    needs: build
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        path: ./artifacts
    
    - name: Display structure of downloaded files
      run: |
        echo "Downloaded artifacts:"
        find ./artifacts -type f -exec ls -la {} \;
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./artifacts/*
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: AugmentCode-Free v${{ github.event.inputs.version || github.ref_name }}
        body: |
          ## 🎉 AugmentCode-Free v${{ github.event.inputs.version || github.ref_name }} - 多平台发布
          
          ### 📦 下载文件
          - **Windows**: `AugmentCode-Free-v${{ github.event.inputs.version || github.ref_name }}-windows.exe`
          - **macOS**: `AugmentCode-Free-v${{ github.event.inputs.version || github.ref_name }}-macos`
          - **Linux**: `AugmentCode-Free-v${{ github.event.inputs.version || github.ref_name }}-linux`
          
          ### 🚀 安装说明
          
          **Windows:**
          1. 下载 `.exe` 文件
          2. 双击运行（可能需要管理员权限）
          3. 首次运行可能需要允许Windows Defender
          
          **macOS:**
          1. 下载 macOS 版本
          2. 添加执行权限: `chmod +x AugmentCode-Free-*-macos`
          3. 运行: `./AugmentCode-Free-*-macos`
          4. 如遇安全提示，请在系统偏好设置中允许
          
          **Linux:**
          1. 下载 Linux 版本
          2. 添加执行权限: `chmod +x AugmentCode-Free-*-linux`
          3. 运行: `./AugmentCode-Free-*-linux`
          
          ### 🔧 技术改进 v${{ github.event.inputs.version || github.ref_name }}
          - ✅ 修复按钮显示键名问题，现在正确显示中文/英文文本
          - ✅ 修复PyInstaller打包缺失语言文件的问题
          - ✅ 完善所有工作线程和补丁操作的国际化支持
          - ✅ 修复补丁状态"已补丁"等硬编码文本
          - ✅ 支持Windows、macOS、Linux多平台自动构建
          
          ### ⚠️ 重要提示
          - 本项目完全开源免费！
          - 如有人向您收费，请立即举报诈骗行为
          - 项目地址：https://github.com/BasicProtein/AugmentCode-Free
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
